patternfly/react-topology

packages/module/src/layouts/BaseLayout.ts, packages/module/src/layouts/ColaGroupsLayout.ts, packages/module/src/layouts/LayoutOptions.ts
**What**:
Fixes https://github.com/patternfly/react-topology/issues/10
**Description**
Only the top level layout should listen for changes to the graph. Sub layouts will run when the top level layout is run.
On layout stop, stop all child layouts.
=> fix(Topology): Fix ColaGroupLayout crash on add

packages/module/src/pipelines/utils/utils.ts
Closes https://github.com/patternfly/react-topology/issues/32
Set a width and height on spacer nodes so that they are not ignored by the layout.
=> fix(pipelines): Set dimensions on spacer nodes

packages/module/src/css/.npmignore, packages/module/src/utils/style-utils.ts
Closes https://github.com/patternfly/react-topology/issues/35
CSS js files are being ignored by .gitignore and hence excluded from the NPM package.
Add a .npmignore file to override .gitignore for NPM
=> fix(css): Add the CSS js files to the npm package

packages/demo-app-ts/src/App.tsx, packages/demo-app-ts/src/Demo.css, packages/demo-app-ts/src/Demos.ts, packages/demo-app-ts/src/components/FailedEdge.tsx, packages/demo-app-ts/src/components/StatusConnectorNode.tsx, packages/demo-app-ts/src/components/SuccessEdge.tsx, packages/demo-app-ts/src/components/statusConnectorsComponentFactory.ts, packages/demo-app-ts/src/components/useSourceStatusAnchor.tsx, packages/demo-app-ts/src/components/useTargetStatusAnchor.tsx, packages/demo-app-ts/src/demos/StatusConnectors.tsx, packages/demo-app-ts/tsconfig.json, packages/module/src/pipelines/utils/draw-utils.ts
Closes #13
Fixes curved line drawing by `integralShapePath` when nodes are offset by less than the curve height.
Adds a complex anchor demo to demonstrate creating nodes with anchors based on offsets and edge types.
=> Fix integralShapePath for almost parallel nodes

packages/demo-app-ts/src/demos/ContextMenus.tsx, packages/demo-app-ts/src/index.tsx, packages/module/src/behavior/withContextMenu.tsx
Closes #15 
Allows the use of a Promise when determining the context menu items when using `withContextMenu`
/cc @jshaughn
=> feature: withContextMenu support for Promise

packages/demo-app-ts/src/utils/useDemoPipelineNodes.tsx, packages/module/src/pipelines/components/nodes/TaskNode.tsx
Closes #65
Adds the ability to show a custom icon before the text in a pipeline `TaskNode`.
=> feature: Add lead icon to task nodes

.gitignore, packages/demo-app-ts/package.json, packages/demo-app-ts/src/App.tsx, packages/demo-app-ts/src/Demo.css, packages/demo-app-ts/src/utils/useTopologyOptions.tsx, packages/module/package.json, packages/module/patternfly-docs/content/examples/TopologyLayouts.md, packages/module/patternfly-docs/content/examples/TopologyLayoutsDemo.tsx, packages/module/patternfly-docs/content/examples/TopologyPipelinesGettingStarted.md, packages/module/patternfly-docs/content/examples/TopologyToolbar.md, packages/module/patternfly-docs/content/examples/TopologyToolbarDemo.tsx, packages/module/patternfly-docs/content/examples/topology-example.css, packages/module/patternfly-docs/content/examples/topology-pipelines-example.css, packages/module/patternfly-docs/patternfly-docs.source.js, packages/module/release.config.js, packages/module/src/behavior/withContextMenu.tsx, packages/module/src/components/TopologyControlBar/TopologyControlBar.tsx, packages/module/src/components/TopologyControlBar/__tests__/__snapshots__/TopologyControlBar.test.tsx.snap, packages/module/src/components/TopologyView/__tests__/TopologyView.test.tsx, packages/module/src/components/TopologyView/__tests__/__snapshots__/TopologyView.test.tsx.snap, packages/module/src/components/contextmenu/ContextSubMenuItem.tsx, packages/module/src/css/topology-components.css, packages/module/src/css/topology-controlbar.css, packages/module/src/css/topology-pipelines.css, packages/module/src/css/topology-side-bar.css, packages/module/src/css/topology-view.css, packages/module/src/pipelines/utils/utils.ts, yarn.lock
Towards #55
Bumps PF dependencies towards PF v5 release adoption.
=> chore(deps): Bump PF deps to latest prerelease

packages/demo-app-ts/src/App.tsx, packages/demo-app-ts/src/demos/Styles.tsx, packages/demo-app-ts/src/utils/styleUtils.ts, packages/module/src/components/edges/DefaultEdge.tsx, packages/module/src/css/topology-components.css, packages/module/src/css/topology-pipelines.css
Fixes #63
Update color styles per [dark theme audit](https://github.com/patternfly/react-topology/issues/49).
/cc @mceledonia @andrew-ronaldson
=> fix: Style updates per dark theme audit

packages/module/src/pipelines/components/nodes/TaskNode.tsx
Closes https://github.com/patternfly/react-topology/issues/73
Wrap updates to node edges in mobx `action`.
=> chore: Fix mobx warnings in TaskNode

packages/module/patternfly-docs/content/examples/TopologyGettingStarted.md
Closes #78 
Update the url to the code for the `Model` type in the getting started doc page.
=> doc: Fix link to model in getting started doc

packages/module/patternfly-docs/content/examples/TopologySelectableDemo.tsx
Towards #88 - verify npm publishes correct v4 prerelease version
=> fix: revert linting update to verify prerelease version

packages/demo-app-ts/src/App.tsx, packages/demo-app-ts/src/components/actionsComponentFactory.tsx, packages/demo-app-ts/src/components/pipelineComponentFactory.tsx, packages/demo-app-ts/src/components/stylesComponentFactory.tsx, packages/demo-app-ts/src/demos/ContextMenus.tsx, packages/demo-app-ts/src/utils/useTopologyOptions.tsx, packages/module/patternfly-docs/content/examples/TopologyContextMenuDemo.tsx, packages/module/src/components/contextmenu/ContextMenu.tsx, packages/module/src/components/contextmenu/ContextSubMenuItem.tsx, packages/module/src/components/contextmenu/index.ts
=> chore: upgrade deprecated components in demo-app

packages/demo-app-ts/src/utils/useTopologyOptions.tsx, packages/module/src/behavior/useDndDrag.tsx, packages/module/src/components/SVGArrowMarker.tsx, packages/module/src/components/nodes/DefaultNode.tsx, packages/module/src/components/svg/SvgDropShadowFilter.tsx, packages/module/src/hooks/useScaleNode.tsx, packages/module/src/layouts/BaseLayout.ts, packages/module/src/utils/svg-utils.ts, packages/module/src/utils/useHover.ts
Closes #96 
Remove the usage of `window` and `global`
No visual changes.
Surge: https://jeff-latest.surge.sh/
=> fix(window): remove the use of global and window

packages/demo-app-ts/src/components/StyleGroup.tsx, packages/demo-app-ts/src/data/generator.ts, packages/demo-app-ts/src/demos/TopologyPackage.tsx, packages/demo-app-ts/src/utils/useTopologyOptions.tsx, packages/module/src/components/groups/DefaultGroup.tsx, packages/module/src/components/groups/DefaultGroupExpanded.tsx
Closes https://github.com/patternfly/react-topology/issues/113
A new property in the DefaultGroup was added to set whether the outline of the group is hulled or rect.
=> added property to set whether the outline is hull or rect

packages/module/scripts/writeClassMaps.js
Closes #118
Prevents TypeScript files from being copied to the dist/{module}/css directory at build time. Still allows type declaration files to be copied.
=> fix(build): prevent index.ts file from being copied into dist

packages/module/src/components/edges/DefaultEdge.tsx
Resolves #122.
When hovering on details level != high:
=> Logic for showing, scaling or hiding the tag on an edge depending on the details level of the graph

packages/demo-app-ts/src/components/DemoFinallyNode.tsx, packages/demo-app-ts/src/components/DemoTaskNode.tsx, packages/demo-app-ts/src/components/StyleGroup.tsx, packages/demo-app-ts/src/components/StyleNode.tsx, packages/demo-app-ts/src/utils/useDemoPipelineNodes.tsx, packages/module/src/pipelines/components/nodes/TaskNode.tsx
Closes #124 
Update to get details level directly from the graph rather that using the `useDetailsLevel` hook so that the scale level is observed and nodes redraw on scale change.
=> fix: reduce node details when at low scale

packages/module/src/Visualization.ts
Closes #130
Configure MobX to isolate global state to allow applications to use multiple versions of MobX.
/cc @jotak
=> fix(mobx): Configure mobx to isolate state

packages/demo-app-ts/src/utils/styleUtils.ts, packages/module/src/components/groups/DefaultGroup.tsx, packages/module/src/components/groups/DefaultGroupCollapsed.tsx, packages/module/src/components/groups/DefaultGroupExpanded.tsx, packages/module/src/components/nodes/DefaultNode.tsx, packages/module/src/components/nodes/labels/NodeLabel.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/types.ts
Closes #
https://github.com/patternfly/react-topology/issues/139
Adds `top` label position in group node
Collapsed Group:
Expanded Groups:
Pipeline task groups:
.
=> feat(label): add support for top label position in groups

packages/module/src/components/groups/DefaultGroup.tsx, packages/module/src/elements/BaseNode.ts
Closes #145 
Fix positioning of child nodes when a collapsed group is expanded.
https://uncollapse-fix.surge.sh
=> fix(collapse):Fix child positions on group expand

packages/demo-app-ts/src/demos/PipelineLayout.tsx, packages/demo-app-ts/src/demos/StatusConnectors.tsx, packages/demo-app-ts/src/utils/usePipelineOptions.tsx, packages/module/src/elements/BaseGraph.ts, packages/module/src/layouts/BaseLayout.ts, packages/module/src/layouts/DagreLayout.ts, packages/module/src/pipelines/components/anchors/TaskNodeSourceAnchor.ts, packages/module/src/pipelines/components/anchors/TaskNodeTargetAnchor.ts, packages/module/src/pipelines/components/edges/TaskEdge.tsx, packages/module/src/pipelines/components/nodes/TaskNode.tsx, packages/module/src/pipelines/decorators/WhenDecorator.tsx, packages/module/src/pipelines/layouts/PipelineDagreLayout.ts, packages/module/src/pipelines/utils/draw-utils.ts, packages/module/src/types.ts
Closes #136 
Closes [UXDENG-216](https://issues.redhat.com/browse/UXDENG-216)
Adds support for top to bottom pipelines layout. Passing `rankdir: 'TB'` to the options for `PipelineDagreLayout` will render the pipeline top to bottom.
https://vertical-pipelines.surge.sh/
=> feat(pipelines): Support top to bottom pipelines

packages/demo-app-ts/src/demos/topologyPackageDemo/DemoContext.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/OptionsContextBar.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/TopologyPackage.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/generator.ts
Fixes the Topology Package demo nesting depth setting. The setting was not being used when creating nodes.
=> chore(demo): fix for nested levels in package demo

package.json
Might resolve the issue with #165
Moves react types dependency to devDeps because of an issue Openshift is having with react types after testing the latest topology prerelease.
Dependency adjustment.
=> fix(deps): Move @types/react from resolutions to devDeps

packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskGroup.tsx, packages/module/src/pipelines/components/anchors/TaskGroupSourceAnchor.ts, packages/module/src/pipelines/components/anchors/TaskGroupTargetAnchor.ts, packages/module/src/pipelines/components/anchors/index.ts, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroupCollapsed.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroupExpanded.tsx, packages/module/src/pipelines/components/groups/index.ts, packages/module/src/pipelines/components/nodes/TaskNode.tsx
Closes #172 
Add ability to hide details of collapsed pipeline groups. Also fixes some edge alignment issues caused by collapsing and re-expanding the pipeline groups.
- [x ] Feature
=> feat(pipelines): Add ability to scale collapsed pipeline groups

packages/module/src/types.ts
Closes #165 
Fixes issue where consumers are receiving a type error  when using an older version for react-types.
=> fix(types): Work around to fix issue with consumers recieving a type error.

packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskGroup.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx
Closes #171 
1. Go to surge link below. 
2. Pipelines -> Pipeline Groups Demo
3. Collapse Execution 2
4. Verify status icon and state are shown on "Execution 2" node. 
https://task-group-status.surge.sh
=> feat(DefaultTaskGroup): support status

packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskEdge.tsx, packages/demo-app-ts/src/demos/pipelineGroupsDemo/PipelineGroupsDemo.tsx, packages/demo-app-ts/src/demos/pipelineGroupsDemo/pipelineGroupsComponentFactory.tsx, packages/module/src/css/topology-components.css, packages/module/src/pipelines/components/edges/TaskEdge.tsx
Closes #187 
Adds `WithSelection` props to `TaskEdge` and styles for selection.
=> feat(pipelines): Add ability and styling for selected task edges

packages/module/src/components/edges/terminals/DefaultConnectorTerminal.tsx
Closes #190
Fix error in determination of incoming location for target arrows on edges with bendpoints.
=> fix(target arrow): Correctly determine incoming point for target connectors

packages/demo-app-ts/src/demos/DemoControlBar.tsx, packages/demo-app-ts/src/demos/pipelineGroupsDemo/PipelineGroupsDemo.tsx, packages/module/src/components/TopologyControlBar/TopologyControlBar.tsx, packages/module/src/elements/BaseGraph.ts, packages/module/src/elements/BaseNode.ts, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/types.ts
Closes #196 
Adds the ability for applications to show an `expand all` and `collapse all` button on the control bar.
The application must handle the callback and call the new `Graph` method `expandAll` or `collapseAll`. If the application is using a pipeline layout with generate spacer nodes and edges, it must recreate the model and relayout the view. 
An example of just how this is done can be found in: [PipelineGroupsDemo.collapseAllCallback](https://github.com/patternfly/react-topology/compare/main...jeff-phillips-18:react-topology:expand-collapse-all?expand=1#diff-c01eab00979c991ae559de70cd8e380f4f26471d0772521471d8c4efb0bb4559R86-R121)
Note that there are 2 new methods added to the `Graph` interface and an optional parameter `leafOnly` to the `getAllChildren` method on the `Node` …
=> feat(ControlBar): Add expand/collapse all buttons

packages/demo-app-ts/src/demos/topologyPackageDemo/TopologyPackage.tsx
Closes #207 
Adds functionality in the demo app `Topology Package Demo` for panning a node into view on selection when it would otherwise be covered by the side panel.
Only adding a demo of existing functionality
=> chore(panIntoView): Add demo of the panIntoView functionality on node selection

packages/module/src/components/nodes/DefaultNode.tsx
Closes #211 
When hovering over a node when zoomed out, the label is brought to the top layer. This causes the transform used on the node to not have effect on the label. We need to set the transform to the same transform used by the node in order to get the same translation and scale.
=> fix(DefaultNode): Correctly scale the node's label on hover when zoomed iyt

packages/module/src/elements/BaseGraph.ts, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/types.ts
Closes #206 
Adds a feature to `focus` on a group after it has been expanded or collapsed.
On expand the group will be shown in the view with the graph set to fit around the group so that the entire expansion can be viewed or be zoomed in on to emphasize the group.
On collapse, the view may be zoomed out so as not to show extra white space due to the collapsing of the group and the group will be centered in the view.
Note that a new method `centerInView` was added to the `Graph` interface and an optional parameter `node` to the `fit` method on the `Graph` interface. Any application that is current implementing these interfaces without extending the base implementation will need to adjust accordingly.
=> feat(pipelines): Add focus on newly expanded/collapsed groups

packages/demo-app-ts/src/demos/pipelinesDemo/DemoTaskNode.tsx, packages/demo-app-ts/src/demos/pipelinesDemo/useDemoPipelineNodes.tsx, packages/module/src/pipelines/components/nodes/TaskNode.tsx
Closes #208
Adds a new customStatusIcon prop to allow for a persisting icon with the correct status icon styling when a node is hovered or zoomed out.  
Default node view:
Low details level/ zoomed out view:
=> feat(pipelines): support customStatusIcon

packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskGroup.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/DemoGroup.tsx, packages/module/src/components/groups/DefaultGroup.tsx, packages/module/src/components/groups/DefaultGroupExpanded.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroupExpanded.tsx
Closes #213 
Adds a `showLabelOnHover` parameter to `DefaultGroup` and `DefaultTaskGroup` to show a group's label on hover. This is useful when an application hides details on zoom out but wants to see the label if the user hovers over the group.
=> feat(group labels): Add ability to show group labels on hover

.eslintignore, packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskGroup.tsx, packages/demo-app-ts/src/demos/pipelineGroupsDemo/createDemoPipelineGroupsNodes.ts, packages/module/src/components/ElementWrapper.tsx, packages/module/src/components/nodes/labels/NodeLabel.tsx, packages/module/src/pipelines/components/anchors/TaskGroupSourceAnchor.ts, packages/module/src/pipelines/components/anchors/TaskGroupTargetAnchor.ts, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroupExpanded.tsx, packages/module/src/pipelines/components/nodes/TaskNode.tsx
Closes #205 
Adds the `centerLabelOnEdge` option to `DefaultTaskGroup`. Setting this to true will ignore the `labelPadding` parameter and instead align the label such that it is centered on the group's border. The source and target anchors are also adjusted to align with the label position.
=> feat(group label): Add ability to center the group's label on the edge

packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskGroup.tsx, packages/demo-app-ts/src/demos/pipelinesDemo/DemoPipelinesGroup.tsx, packages/module/src/components/nodes/labels/NodeLabel.tsx, packages/module/src/components/nodes/labels/index.ts, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/module/src/pipelines/components/groups/DefaultTaskGroupExpanded.tsx, packages/module/src/pipelines/components/groups/TaskGroupPillLabel.tsx, packages/module/src/pipelines/components/groups/index.ts, packages/module/src/pipelines/components/nodes/TaskNode.tsx, packages/module/src/pipelines/components/nodes/TaskPill.tsx, packages/module/src/pipelines/components/nodes/index.ts
Towards #204 
These updates add pill styling to group node labels as requested per RHOAI UX. Adds TaskPill logic and support for custom `GroupLabelComponent`
=> feat(pipelines): add support for custom `GroupLabelComponent`

packages/module/src/pipelines/components/nodes/TaskPill.tsx
Closes #227
1. Go to http://custom-status-fix.surge.sh 
2. Navigate to PIpelines -> Task Nodes demo
3. Verify that `customStatusIcon` is applied
Before
After
=> fix(TaskPill): fix customStatusIcon bug

packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskGroup.tsx, packages/demo-app-ts/src/demos/pipelineGroupsDemo/DemoTaskNode.tsx, packages/demo-app-ts/src/demos/pipelineGroupsDemo/createDemoPipelineGroupsNodes.ts, packages/module/src/pipelines/components/groups/DefaultTaskGroup.tsx
Closes #240 
Adds the `customStatusIcon` property to the DefaultTaskGroup. This property is useful only for collapsed groups, or if using a GroupLabelComponent that accepts a customStatus icon, such as TaskGroupPillLabel.
/cc @jpuzz0
=> feat(DefaultTaskGroup): Allow for a custom status icon in DefaultTaskGroup

packages/demo-app-ts/src/demos/pipelinesDemo/DemoTaskNode.tsx, packages/demo-app-ts/src/demos/stylesDemo/StyleNode.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/DemoNode.tsx, packages/module/src/components/nodes/DefaultNode.tsx, packages/module/src/components/nodes/labels/NodeLabel.tsx
Closes #247 
Adds the option to not raise the label when the node is hovered. This keeps the label on the same layer as the node which avoids getting a mouse leave event when moving from the node to the label. For applications that are raising the node to the TOP_LEVEL on hover, they should pass `raiseLabelOnHover={false}` to the `DefaultNode`.
Also, when the context menu is open, treat the node label the same as if hovering so that it remains visible and un-truncated while the context menu is open.
=> fix(context menu): Fix for context menu use when zoomed out

packages/demo-app-ts/src/demos/topologyPackageDemo/AreaDragHint.css, packages/demo-app-ts/src/demos/topologyPackageDemo/AreaDragHint.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/TopologyPackage.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/demoComponentFactory.tsx, packages/module/src/behavior/index.ts, packages/module/src/behavior/useAreaSelection.tsx, packages/module/src/behavior/usePanZoom.tsx, packages/module/src/components/GraphComponent.tsx, packages/module/src/css/topology-components.css, packages/module/src/elements/BaseGraph.ts, packages/module/src/types.ts
Closes #222 
Adds the ability to drag an area on the graph.
Added events for:
- GRAPH_AREA_DRAGGING_EVENT - When user is dragging an area on the graph
- GRAPH_AREA_SELECTED_EVENT - When the user completed the selection of an area
Adds a hook to allow area selection via `withAreaSelection`. This takes key modifiers that can be handled separately so applications can do different things based on the shift key, cntrl key, etc.
Adds two methods to the `Graph` element:
- zoomToSelection : pass it the values from the `GRAPH_AREA_SELECTED_EVENT` to zoom to that area
- nodesInSelection : pass it the values from the `GRAPH_AREA_SELECTED_EVENT` to get all nodes in that area
The Topology Package demo is updated to add both shift and cntrl drag and to zoom for cntrl and select nodes for shift. Also …
=> feat(graph): Add selection based zoom

packages/demo-app-ts/src/demos/topologyPackageDemo/DemoNode.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/OptionsContextBar.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/generator.ts, packages/module/src/components/nodes/DefaultNode.tsx, packages/module/src/components/nodes/labels/NodeLabel.tsx, packages/module/src/pipelines/components/nodes/TaskNode.tsx, packages/module/src/pipelines/components/nodes/TaskPill.tsx
Closes #237 
Adds prop `hideContextMenuKebab` to toggle context menu via Shift + Right Click only. cc @ferhoyos
To test:
1. In `DemoNode.tsx`, add `hideContextMenuKebab` as a prop of the `DefaultNode` component. In the demo app, go to Topology Package and in the "Node Options" dropdown, check Labels and Context Menus. 
2. In `DemoTaskNode.tsx`, add `hideContextMenuKebab` as a prop of the `TaskNode` component. In the demo app, go to Pipelines -> Task Nodes and select "Context Menus" in the toolbar.
=> feat(context menu): Add support to hide the kebab toggle in the context menu

packages/module/src/components/nodes/labels/LabelBadge.tsx, packages/module/src/css/topology-components.css, packages/module/src/pipelines/components/groups/DefaultTaskGroupCollapsed.tsx, packages/module/src/pipelines/components/nodes/TaskBadge.tsx
Closes #256 
Updates the colors for the line and background for the line for edges when selected and/or hovered.
Also updates the badges for labels to set style rather than fill and stroke properties so they don't get overridden by styling.
https://connector-styles.surge.sh/
=> fix(edges): Fix colors for selected/hovered edges for light and dark themes

packages/demo-app-ts/src/demos/topologyPackageDemo/DemoGroup.tsx, packages/module/src/components/groups/DefaultGroup.tsx, packages/module/src/components/groups/DefaultGroupCollapsed.tsx, packages/module/src/components/groups/DefaultGroupExpanded.tsx
Closes #254 
Adds prop hideContextMenuKebab to toggle context menu via Shift + Right Click only. cc @ferhoyos
To test:
In StyleGroup.tsx, add `hideContextMenuKebab` as a prop of the `DefaultGroup` component. In the demo app, go to Styles -> Groups -> Collapsible Groups. Verify the menu kebab is hidden and can be toggled with Shift + Right click.
Before:
After:
=> Feat(context menu): Add the hideContextMenuKebab option to groups

packages/module/src/components/groups/DefaultGroup.tsx, packages/module/src/components/groups/DefaultGroupCollapsed.tsx, packages/module/src/components/groups/DefaultGroupExpanded.tsx
Closes #255
To test, add `labelClassName="test"` to the <DefaultGroup> component in `DemoGroup.tsx`. Verify the custom class is visible in Topology Package via the demo app.
=> feat(groups): Add the labelClassName prop to groups

README.md, packages/demo-app-ts/README.md, packages/module/release.config.js
Onboarding to the project, and trying out the awesome demo. Wanted to make a few small improvements to the docs.
See the GitHub UI for the rich markdown previews; 
https://github.com/patternfly/react-topology/blob/57765372d242b57321e6ad220ab72d9e7c42b1cb/packages/demo-app-ts/README.md
This PR should also fix the demo image being a 404:
> <img width="371" alt="demo module screenshot is not rendering, due to a relative path bug." src="https://github.com/user-attachments/assets/2b1ac3aa-31ae-4870-8dd8-6812ac35d7b5"/>
=> Update demo readme and main readme

packages/module/src/components/contextmenu/ContextSubMenuItem.tsx
Closes #270 
The root issue ended up being that `Dropdown` also implements a `Popper`, so although the topology portal goes to the correct element in the DOM, the portal inside the Dropdown goes to `document.body`. Since the Dropdown is a child of the topology popper, it takes precedence, causing the children to go to the body instead of its intended location
https://github.com/user-attachments/assets/ddce12d2-4c2f-48cc-85a2-6874a8c8ea3c
=> fix(ContextSubMenuItem): fix popper container

packages/module/src/components/contextmenu/ContextMenu.tsx
Closes #238 
Adds an effect to force a recompute of the context menu position when the context menu items change.
=> fix(ContextMenu): Update context menu placement on items change

packages/demo-app-ts/src/demos/DragDrop.tsx, packages/demo-app-ts/src/demos/topologyPackageDemo/demoComponentFactory.tsx, packages/module/src/components/edges/DefaultEdge.tsx, packages/module/src/components/factories/components/componentUtils.ts, packages/module/src/css/topology-components.css
Closes [Topology - Enable DefaultEdge as drop target](https://github.com/patternfly/react-topology/issues/259)
Adds parameters and styles to `DefaultEdge` for drop target indication.
Adds `edgeDropTargetSpec`
Updates the demo app to demo the new feature
=> feat: Enable DefaultEdge as drop target

packages/demo-app-ts/src/demos/topologyPackageDemo/demoComponentFactory.tsx, packages/module/src/components/contextmenu/ContextSubMenuItem.tsx, packages/module/src/css/topology-components.css
Closes #293 
Updates the context menu's submenu items css to set the min-width to `auto` in order to prevent truncation.
Adds submenu items to the context menus in the topology package demo.
Adds a context menu to the graph in the topology package demo.
=> fix(ContextSubMenuItem): Remove truncation of context submenu items

packages/module/src/components/nodes/DefaultNode.tsx
Closes #292
Fixes an issue where the node label flickers on hover and leaving the label after hovering does not remove the hover treatment.
Added a hover check for the label on DefaultNode to specifically watch the hover state on the label.
=> fix(DefaultNode): Fix label flicker on hover
