package.json
packages/demo-app-ts/src/App.tsx
packages/demo-app-ts/src/Demos.ts
packages/demo-app-ts/webpack.config.js
yarn.lock

**What:**
Add surge to allow manual creation of surge site
See in action: https://topology-demo-latest.surge.sh

Add surge (manual only)

---

packages/module/release.config.js

feat(release): Enable release from extracted repo

---

packages/module/src/components/edges/DefaultEdge.tsx
packages/module/src/components/factories/components/componentUtils.ts

fix: Don't display edges inside collapsed groups

---

packages/module/src/css/topology-components.css

fix(topology): Keep node outline on hover

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adds templates for PRs and Issues
- [x ] Other (please describe): git templates

chore(templates): Add git PR and issue templates

---

packages/module/src/css/topology-pipelines.css
packages/module/src/pipelines/utils/StatusIcon.tsx
packages/module/src/pipelines/utils/utils.ts

Fixes:
Bug  - https://github.com/patternfly/react-topology/issues/12
Screenshots:

fix(pipelines): update running and pending icon colors

---

packages/module/patternfly-docs/content/examples/TopologyAnchors.md
packages/module/patternfly-docs/content/examples/TopologyContextMenu.md
packages/module/patternfly-docs/content/examples/TopologyControlBar.md
packages/module/patternfly-docs/content/examples/TopologyCustomEdges.md
packages/module/patternfly-docs/content/examples/TopologyCustomNodes.md
packages/module/patternfly-docs/content/examples/TopologyDragDropDemo.md
packages/module/patternfly-docs/content/examples/TopologyGettingStarted.md
packages/module/patternfly-docs/content/examples/TopologyLayouts.md
packages/module/patternfly-docs/content/examples/TopologyPanZoom.md
packages/module/patternfly-docs/content/examples/TopologyPipelinesGettingStarted.md
packages/module/patternfly-docs/content/examples/TopologySelectable.md
packages/module/patternfly-docs/content/examples/TopologySidebar.md
packages/module/patternfly-docs/content/examples/TopologyToolbar.md
packages/module/src/components/edges/DefaultEdge.tsx
packages/module/src/components/groups/DefaultGroup.tsx

Closes #50 
Fixes the links to the GitHub source code for the documentation demos

chore(doc): Fix links to demo code source

---

packages/module/package.json

PF v5 latest pre release

---

packages/module/package.json
packages/module/release.config.js

Closes #55
Release CI update to be prerelease versions rather than alpha, also some slight dependency tweaks.

chore(ci-release): Update release config from alpha to prerelease

---

packages/module/src/Visualization.ts
packages/module/src/components/ElementWrapper.tsx
packages/module/src/types.ts

Closes #75 
Updates the return type for ComponentFactory to allow for specific element subclasses

fix(componentFactory): Update component factory return type

---

packages/demo-app-ts/src/demos/TopologyPackage.tsx
packages/module/src/elements/BaseGraph.ts

Closes #77 
Update the value that has changed before firing the GRAPH_POSITION_CHANGE_EVENT

fix(event): Update values before firing GRAPH_POSITION_CHANGE_EVENT

---

packages/demo-app-ts/src/demos/TopologyPackage.tsx
packages/module/src/layouts/BaseLayout.ts
packages/module/src/layouts/BreadthFirstLayout.ts
packages/module/src/layouts/ColaGroupsLayout.ts
packages/module/src/layouts/ColaLayout.ts
packages/module/src/layouts/ConcentricLayout.ts
packages/module/src/layouts/DagreLayout.ts
packages/module/src/layouts/ForceLayout.ts
packages/module/src/layouts/GridLayout.ts

Closes #79 
Update layouts to fire the GRAPH_LAYOUT_END_EVENT only after the layout is complete

fix(event): Fix firing of GRAPH_LAYOUT_END_EVENT

---

packages/demo-app-ts/package.json
packages/module/package.json
yarn.lock

Bumps PatternFly versions to their (hopefully) final release candidate versions

chore(deps): Bump PatternFly deps to latest release candidates

---

packages/demo-app-ts/src/App.tsx
packages/module/patternfly-docs/content/examples/TopologyLayouts.md
packages/module/patternfly-docs/content/examples/TopologyLayoutsDemo.tsx
packages/module/patternfly-docs/content/examples/TopologyToolbar.md
packages/module/patternfly-docs/content/examples/TopologyToolbarDemo.tsx

Towards #69 
Updates deprecated v4 components to their v5 counterparts

Update deprecated components

---

.github/workflows/release.yml
packages/module/package.json
packages/module/release.config.js

Towards #88 
v4 config updates as part of branch retirement process

Config updates to v4

---

.github/workflows/release.yml
packages/module/release.config.js

Towards #88 
Config updates to v5 branch

Config updates to retire v5

---

.github/workflows/check-pr.yml

fix: update check-pr.yml to run on push to v4

---

.github/workflows/check-pr.yml

fix: remove v5 branch from check-pr.yml

---

packages/module/patternfly-docs/content/examples/TopologySelectableDemo.tsx

Ran prettier on file to test correct prerelease version
Towards #88 , testing if prerelease versions are now synced (should be prerelease-v4.93.7)

test prerelease versions with linting update

---

packages/module/release.config.js

chore: remove dryRun from v4

---

packages/demo-app-ts/package.json
packages/module/package.json
packages/module/src/components/TopologyControlBar/__tests__/__snapshots__/TopologyControlBar.test.tsx.snap
packages/module/src/components/TopologyView/__tests__/__snapshots__/TopologyView.test.tsx.snap
yarn.lock

chore: prepare for q3 release

---

.github/workflows/check-pr.yml
.github/workflows/promote.yml
.github/workflows/release.yml
jest.config.js
package.json
packages/module/package.json
packages/module/release.config.js
yarn.lock

Update CI and semantic release for v6 branch

---

packages/demo-app-ts/package.json
packages/module/package.json
yarn.lock

Updates v6 branch PF dependencies to latest patternfly v6

Update to PF dependencies to latest V6

---

.github/workflows/build-lint-test.yml
.github/workflows/build.yml
.github/workflows/release.yml
packages/module/package.json
packages/module/src/components/TopologyControlBar/__tests__/__snapshots__/TopologyControlBar.test.tsx.snap
yarn.lock

Fix node version for build testing

chore: v6 update node version for test builds

---

packages/module/src/layouts/BreadthFirstLayout.ts
packages/module/src/layouts/GridLayout.ts

fix(layouts): remove unused var gridOptions

---

.github/workflows/extensions.yml

Updated github actions in order to put new issues into [PatternFly Issues](https://github.com/orgs/patternfly/projects/7) project.

chore(pf-issues): Updated code to put issues into Patternfly Issues projects

---

packages/module/src/pipelines/elements/index.ts
packages/module/src/pipelines/index.ts

Closes #169 
Add  pipelineElementFactory and BasePipelineNode to package exports.

fix(exports): export pipelineElementFactory and BasePipelineNode

---

.github/upload-preview.js
.github/workflows/pr-preview.yml

Closes #158 
Adding PR previews helps with reviewing changes, especially for designers

feat(actions): Add PR previews

---

.github/workflows/pr-preview.yml
packages/module/package.json
yarn.lock

The package.json file in v6 currently has merge conflict markers, this fix removes them

chore(package.json) Fix V6 package.json file

---

packages/demo-app-ts/package.json
packages/demo-app-ts/src/App.tsx
packages/module/package.json
packages/module/patternfly-docs/pages/index.js
packages/module/src/components/TopologySideBar/TopologySideBar.tsx
yarn.lock

fix: another beta bump

---

package.json
packages/module/package.json
packages/module/src/components/nodes/labels/LabelBadge.tsx
packages/module/src/components/svg/SvgDropShadowFilter.tsx
packages/module/src/pipelines/components/nodes/TaskBadge.tsx
yarn.lock

Update to the latest release candidate.

fix: updated with latest pf v6 release candidate.

---

packages/module/src/anchors/AbstractAnchor.ts

chore(typo): Fix small typo in AbstractAnchor.ts

---

packages/demo-app-ts/src/demos/pipelinesDemo/DemoTaskNode.tsx
packages/demo-app-ts/src/demos/stylesDemo/StyleNode.tsx
packages/demo-app-ts/src/demos/topologyPackageDemo/AreaDragHint.css
packages/demo-app-ts/src/demos/topologyPackageDemo/AreaDragHint.tsx
packages/demo-app-ts/src/demos/topologyPackageDemo/DemoNode.tsx
packages/demo-app-ts/src/demos/topologyPackageDemo/OptionsContextBar.tsx
packages/demo-app-ts/src/demos/topologyPackageDemo/TopologyPackage.tsx
packages/demo-app-ts/src/demos/topologyPackageDemo/demoComponentFactory.tsx
packages/demo-app-ts/src/demos/topologyPackageDemo/generator.ts
packages/module/src/behavior/index.ts
packages/module/src/behavior/useAreaSelection.tsx
packages/module/src/behavior/usePanZoom.tsx
packages/module/src/components/GraphComponent.tsx
packages/module/src/components/nodes/DefaultNode.tsx
packages/module/src/components/nodes/labels/NodeLabel.tsx
packages/module/src/css/topology-components.css
packages/module/src/elements/BaseGraph.ts
packages/module/src/pipelines/components/nodes/TaskNode.tsx
packages/module/src/pipelines/components/nodes/TaskPill.tsx
packages/module/src/types.ts

Closes #251 
Updates main with fixes in the v5 branch. 
Applies all changes from:
- [feat(graph): Add selection based zoom](https://github.com/patternfly/react-topology/pull/248)
- [fix(context menu): Fix for context menu use when zoomed out](https://github.com/patternfly/react-topology/pull/249)
- [feat(context menu): Add support to hide the kebab toggle in the context menu ](https://github.com/patternfly/react-topology/pull/250)

feat(update): cherry pick missing v5 updates onto main

---

packages/demo-app-ts/src/demos/topologyPackageDemo/DemoGroup.tsx
packages/module/release.config.js
packages/module/src/components/groups/DefaultGroup.tsx
packages/module/src/components/groups/DefaultGroupCollapsed.tsx
packages/module/src/components/groups/DefaultGroupExpanded.tsx

Closes #264 
Applies changes from 
https://github.com/patternfly/react-topology/pull/261
https://github.com/patternfly/react-topology/pull/263

feat(update): cherry pick v5 updates onto main 

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/devX_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/tech_debt_request.md

Closes #267 
Adds issue types to prefill "Create issue" form as done in https://github.com/patternfly/patternfly-react/tree/main/.github/ISSUE_TEMPLATE.

feat: add issue templates for bug reports and feature requests

---

packages/demo-app-ts/package.json
packages/demo-app-ts/src/App.tsx
yarn.lock

Includes Snyk update from #233. 
Resolve build errors in demo-app due to deprecated react-router-dom v5 components after v6 update.

Update react-router-dom v5 components to v6 for build compatibility

---

packages/module/src/components/contextmenu/ContextSubMenuItem.tsx

Minor follow up for #270 to clean up the types. Functionally no code changes
n/a

style(ContextSubMenuItem): remove TS type assertions

---

README.md

Closes https://github.com/patternfly/pf-roadmap/issues/260

docs: Update README to include guidance for AI generated code

---

packages/module/src/pipelines/components/nodes/TaskPill.tsx

Closes #288 
To test, start the demo app and navigate to Pipeline Layout in the left nav.
Before:
After:

fix(task pill): fix icon alignment
